name: Wandering Monster
favicon: null
layout_spectrum: 0.09746
typography_spectrum: 0.5
title: Wandering Monster
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
