name: null
favicon: null
layout_spectrum: 0.43896
typography_spectrum: 0.53164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad9de'
    - '#0b0d0c'
    - '#a5a8af'
    - '#5f6065'
    - '#2a2f29'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
